feat(frontend): data mutations
ChatSift/website pull request #14
Opened 2022-11-20 12:52 UTC by didinele

2022-11-21 14:11 UTC, JohnyTheCarrot requested changes
I'd love to see us upload only the changes in the config rather than the entire config when we send a request.
see patch file in discord

2022-11-21 14:11 UTC, JohnyTheCarrot commented on packages/frontend/src/components/Config/ConfigForm/index.tsx
> +		onMutate: () => {
Any reason we can't just assign the function to the property immediately, without wrapping it in another function first?

2022-11-21 14:11 UTC, JohnyTheCarrot commented on packages/frontend/src/utils/fetch.ts
> +		body: body ? JSON.stringify(body) : (body as BodyInit),
Would prefer to see a more explicit check against null or undefined, unless it can be both in which case it is too verbose and you can disregard me.

2022-11-21 17:00 UTC, didinele commented on packages/frontend/src/components/Config/ConfigForm/index.tsx
> +		onMutate: () => {
Not really, just the idea that we might do more there in the future, in which case we're left with a cleaner git diff/git blame.

2022-11-22 08:04 UTC, JohnyTheCarrot approved these changes
thanks obama

2022-11-22 08:15 UTC, OfficialSirH commented
> thanks obama
all in a day's work
![download](https://user-images.githubusercontent.com/66775276/203260726-201a214a-c506-452a-9975-c8906a4fe2a0.jpg)

2022-11-22 13:55 UTC, merged